### ISSUE TITLE
Double quote issue

### ISSUE THREAD

**Issue by przemkalit** [redhat-cop/aap_configuration_extended#2]
## Summary

I've discovered that the commit 1dc1820d6452ff9208fcf75463dff8869465b975 introduces a bug where if there is a `"` inside the survey question, it will break the YAML.

Shouldn't there be an error related to broken YAML in the filetree_read? 
While debugging the issue, we had to review the controller_templates variable.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

N/A

## OS / ENVIRONMENT

N/A 
## Desired Behavior

Job template is properly exported.

## Actual Behavior
Broken yaml:
```yaml
survey_spec_contents:
  description: ""
  name: ""
  spec:
    - choices: ""
      default: ""
      max: 1024
      min: 0
      new_question: true
      question_description: "Comma separated list of lint rules to skip. Both specific checks and general rules can be skipped, i.e.: "name[missing],fqcn"."
      question_name: Rules to skip
      required: false
      type: text
      variable: skip_rules
```

## STEPS TO REPRODUCE

1) Create JT with survey that is having question with double quote inside.
2) Export the JT.
3) Valid Yaml.
