### ISSUE TITLE
Extra vars yaml issue

### ISSUE THREAD

**Issue by przemkalit** [redhat-cop/aap_configuration_extended#26]
## Summary

Hey, 

There is an issue with exporting the extra vars, it is changing the order of variables in structure to alphabetical. Moreover it sometimes do something like this (probably because of rearranging variables):

![image](https://github.com/user-attachments/assets/02e150fc-5c99-4c71-a60d-c0a2e0793a8c)

From what I've tested the culprit is the `from_yaml | to_nice_yaml(indent=2)`

## Issue Type

- Bug Report

## Ansible, Collection, Controller details
Current versions

## OS / ENVIRONMENT

RH9
## Desired Behavior
Extra vars are properly exported.

## Actual Behavior

Source extra vars:
```yaml
_job_events_use_cases:
  - name: unknown use case
    when:
      matches:
        - unknown use case - no match found with knowledge database
    actions:
      - >-
        just an example
  - name: '!well-known use case, no action needed'
    when:
      matches:
        - 'account_name .+ is not a valid account, cannot get SID'
    actions:
      - >-
        another example
```

Exported extra_vars:
```yaml
_job_events_use_cases:
  - actions:
      - >-
        just an example
    name: unknown use case
    when:
      matches:
        - unknown use case - no match found with knowledge database
  - actions:
      - >-
        another example
    name: '!well-known use case, no action needed'
    when:
      matches:
        - account_name .+ is not a valid account, cannot get SID

```

## STEPS TO REPRODUCE

1) Create JT with long list of extra vars provided in source example
2) Export the JT with filetree_create
