### ISSUE TITLE
How to correctly run filetree_create against AAP 2.5 cluster (multiple hosts)

### ISSUE THREAD

**Issue by cidrbl0ck** [redhat-cop/aap_configuration_extended#95]
## Summary

Trying to run filetree_create against an "Enterprise" architecture setups of AAP 2.5, meaning all external DB's, and 2 hosts per role: gateway, controller, hub and eda. 
Unsure of what the vars are expecting in a non-single host hybrid configuration.

Cannot extrapolate what's required from example playbook and inventory.

So trying to use the example filetree_create.yml playbook as the basis for building my own however the vars are confusing. Well controller_username/password and verify_ssl are obvious. But controller_host is not. 

I have tried defining aap_hostname as either the automationgateway_main_url or the inventory group for the automatoncontrollers. Neither works. Judging from some of the tasks, both of these are used but also the FQDN urls of the other hosts too?

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console (paste below)
ansible --version
ansible [core 2.15.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True

ansible-galaxy collection list
# /home/runner/.ansible/collections/ansible_collections
Collection                      Version     
------------------------------- ------------
ansible.platform                2.5.20250326
infra.aap_configuration         3.1.0       

# /usr/share/ansible/collections/ansible_collections
Collection                      Version     
------------------------------- ------------
amazon.aws                      6.4.0       
ansible.controller              4.5.19      
ansible.netcommon               6.0.0       
ansible.network                 3.0.0       
ansible.posix                   1.5.4       
ansible.scm                     2.0.0       
ansible.security                2.0.0       
ansible.snmp                    2.0.0       
ansible.utils                   5.1.2       
ansible.windows                 1.14.0      
ansible.yang                    2.0.0       
arista.eos                      7.0.0       
cisco.asa                       5.0.0       
cisco.ios                       6.1.0       
cisco.iosxr                     7.0.0       
cisco.nxos                      6.0.0       
cloud.common                    2.1.2       
cloud.terraform                 1.1.1       
frr.frr                         2.0.2       
ibm.qradar                      3.0.0       
junipernetworks.junos           6.0.0       
kubernetes.core                 3.0.1       
microsoft.ad                    1.1.0       
openvswitch.openvswitch         2.1.1       
redhat.amq_broker               1.3.0       
redhat.data_grid                1.3.1       
redhat.eap                      1.3.1       
redhat.insights                 1.3.0       
redhat.jws                      2.0.0       
redhat.openshift                2.3.0       
redhat.openshift_virtualization 1.2.3       
redhat.redhat_csp_download      1.2.2       
redhat.rhbk                     2.2.2       
redhat.rhel_idm                 1.10.0      
redhat.rhel_system_roles        1.21.1      
redhat.rhv                      2.4.2       
redhat.runtimes_common          1.1.3       
redhat.sap_install              1.2.1       
redhat.satellite                3.10.0      
redhat.satellite_operations     1.3.0       
redhat.sso                      1.3.0       
sap.sap_operations              1.0.4       
servicenow.itsm                 2.1.0       
splunk.es                       3.0.0       
trendmicro.deepsec              3.0.0       
vmware.vmware_rest              2.3.1       
vyos.vyos                       4.0.2 
Controller version

```

- ansible installation method: one of source, pip, OS package, EE

RPM non-bundle 

## OS / ENVIRONMENT
All platform hosts are RHEL9
NLB fronting
EC2 (all 8 hosts)
RDS instance housing all db's for all roles
EFS mount for PAH host

Vanilla 2.5.8 installation, not an upgrade.

## Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

My playbook is:

# filetree-created
```
---
- hosts: all
  gather_facts: false
  vars:
    aap_username: cac_user # "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: xxxx # "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "https://{{ inventory_hostname }}"
    main_gateway_url: "https://ansible-dev.domain.net"
    aap_validate_certs: "no" # "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"

  pre_tasks:
    - name: "Display the hosts read from inventory"
      ansible.builtin.debug:
        msg: "Targeting host: {{ item }}"
      with_items: "{{ ansible_play_hosts }}"

    - name: "Setup authentication (block)"
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "{{ main_gateway_url }}/api/gateway/v1/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always
      delegate_to: localhost

  roles:
    - /etc/ansible/roles/aap_configuration_extended/filetree_create

  post_tasks:
    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://ansible-dev/{{ aap_oauthtoken_url }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ aap_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined

```
Inventory file:

```
---
all:
  children:
    dev:
      children:
        automationcontrollers:
          hosts:
            use2-aaphostd03.domain.net:
              #ansible_host: 11.2.3.1
            use2-aaphostd04.domain.net:
              #ansible_host: 1.2.3.2

        automationhub:
          hosts:
            use2-aaphostd05.domain.net:
              #ansible_host: 1.2.3.3
            use2-aaphostd06.domainnet:
              #ansible_host: 1.2.3.4

        automationedacontroller:
          hosts:
            use2-aaphostd07.domain.net:
              #ansible_host: 1.2.3.5
            use2-aaphostd08.domain.net:
              #ansible_host: 1.2.3.6

        automationgateway:
          hosts:
            use2-aaphostd01.domain.net:
              #ansible_host: 1.2.3.7
            use2-aaphostd02.domain.net:
              #ansible_host: 1.2.3.8
  vars:
    ansible_user: user_account   
    ansible_password: xxxxx

```

```console (error)

```

## STEPS TO REPRODUCE

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```
